
#+STARTUP: content

* Архивы
** архивирование
Архив ZIP

# архивирование файла
zip архив.zip файл
# архивирование директории
zip -r архив.zip директория/
# повышение уровня сжатия
zip -0 архив.zip файл
zip -9 архив.zip файл
# защита архива паролем
# не рекомендуемая опция, показывает пароль
zip -P пароль архив.zip файл
# безопасная опция, пароль запрашивается и скрывается при вводе
zip -e архив.zip файл
# разархивирование
unzip архив.zip
# детальный вывод информации при распаковке
unzip -v архив.zip
# получение списка содержимого архива
unzip -l архив.zip
# проверка архива на повреждение
atoolunzip -t архив.zip

Архив TAR

# архивирование файла или директории без сжатия
tar -cf архив.tar файл
# дополнительный ключ "v", для подробного вывода процесса архивации
tar -cvf архив.tar директория/
# архивирование с использованием сжатия gzip
tar -zcvf архив.tar.gz файл
tar -zcvf архив.tar.gz директория/
# архивирование с использованием сжатия bzip2
tar -jcvf архив.tar.bz2 файл
tar -jcvf архив.tar.bz2 директория/
# проверка архива gzip без распаковки
tar -zvtf архив.tar.gz
# проверка архива bzip2 без распаковки
tar -jvtf архив.tar.bz2
# распаковка архива gzip
tar -zxvf архив.tar.gz
# распаковка архива bzip2 с указанием конечной папки для файлов
tar -jxvf архив.tar.bz2 директория/

Архив 7z

# устанавливаем
sudo apt-get install p7zip p7zip-full
#архивируем
7z a arch.7z file01.foo file02.foo
# распаковка
7z x arch.7z
7z x arch.7z -o/куда_извлекать
# просмотр архива
7z l arch.7z
7z l -slt arch.7z

atool

# установка
sudo apt-get install atool
# распаковка
aunpack foobar.tar.gz
# архивирование
apack myarchive.zip file1 file2

Архив LZMA

# установка
sudo aptitude install lzma
# Упаковать файл. Внимание! архивируется сам файл,
# т.е. из файла получится архив! самого файла после упаковки не будет!
lzma -z filename
# Распаковка
lzma -d filename.lzma

** Архив 7z
  # устанавливаем
    sudo apt-get install p7zip p7zip-full
    #архивируем
    7z a arch.7z file01.foo file02.foo
    # распаковка
    7z x arch.7z
    7z x arch.7z -o/куда_извлекать
    # просмотр архива
    7z l arch.7z
    7z l -slt arch.7z
** Архив LZMA
# установка
    sudo aptitude install lzma
    # Упаковать файл. Внимание! архивируется сам файл,
    # т.е. из файла получится архив! самого файла после упаковки не будет!
    lzma -z filename
    # Распаковка
    lzma -d filename.lzma
** Архив RAR
  # упаковка
    rar a архив.rar директория/
  # распаковка
    unrar архив.rar
** Архив TAR
 # архивирование файла или директории без сжатия
    tar -cf архив.tar файл
    # дополнительный ключ "v", для подробного вывода процесса архивации
    tar -cvf архив.tar директория/
    # архивирование с использованием сжатия gzip
    tar -zcvf архив.tar.gz файл
    tar -zcvf архив.tar.gz директория/
    # архивирование с использованием сжатия bzip2
    tar -jcvf архив.tar.bz2 файл
    tar -jcvf архив.tar.bz2 директория/
    # проверка архива gzip без распаковки
    tar -zvtf архив.tar.gz
    # проверка архива bzip2 без распаковки
    tar -jvtf архив.tar.bz2
    # распаковка архива gzip
    tar -zxvf архив.tar.gz
    # распаковка архива bzip2 с указанием конечной папки для файлов
    tar -jxvf архив.tar.bz2 директория/

    # Архивация группы каталогов в MC 
    tar -cvzf archive.tar.gz /home/test

    Выделить группу каталогов и отправить их назавания в консоль:
    1. выделить список папок, что нужно заархивировать
    2. перейти в соседнюю панель
    3. нажать CTRL+X+T
    4. перейти обратно в соседнюю панель, нажать Enter 

    # Для распаковки меняем флаг «c» на «x» и убираем «z»:

    tar -xvf archive.tar.gz
** Архив ZIP
# архивирование файла
    zip архив.zip файл
    # архивирование директории
    # повышение уровня сжатия
    zip -0 архив.zip файл
    zip -9 архив.zip файл
    # защита архива паролем
    # не рекомендуемая опция, показывает пароль
    zip -P пароль архив.zip файл
    # безопасная опция, пароль запрашивается и скрывается при вводе
    zip -e архив.zip файл
    # разархивирование
    unzip архив.zip
    # детальный вывод информации при распаковке
    unzip -v архив.zip
    # получение списка содержимого архива
    unzip -l архив.zip
    # проверка архива на повреждение
    unzip -t архив.zip
** Архив_atool
Используем atool — это сценарий для управления файловыми архивами различных типов. Теперь вам не нужно запоминать, что архивы 7z нужно распаковывать одной командой, а rar другой.

    # установка
    sudo apt-get install atool
    # распаковка
    aunpack foobar.tar.gz
    # архивирование
    apack myarchive.zip file1 file2
** ranger_команды_архивации
map ex extract
map ec compress
** извлечение архивов в ranger
1l - будет извлечен, 2l - покажет диалог «открыть с» и 3l - откроет его в Vim
** Создание и распаковка архивов в Linux
Создание tar-архива без сжатия

Для создания такого архива используется команда:

tar -cf filename.tar file1 file2 fileN

Параметр —cf отвечает за создание архива filename.tar, в который войдут указанные файлы. Вместо файлов могут быть указаны и директории.
Создание архива с использованием сжатия

Поскольку для сжатия доступны как минимум два метода, для использования каждого из них используется отдельный набор параметров.

Пример сжатия Gzip:

tar -cvzf filename.tar.gz dir_name

В данном случае мы попытались запаковать папку dir_name в архив filename.tar.gz. Из указанных параметров -z указывает на использование метода Gzip, а -v выводит результаты процесса создания архива с указанием упакованных файлов или папок.

Пример сжатия Bzip2:

tar -cvjf filename.tar.bz2 dir_name

Данная команда аналогична предыдущей и имеет отличие в параметре –j, т.к. именно он отвечает за использование метода сжатия Bzip2.
Распаковка архива

Для того, чтобы распаковать архив, используется команда:

tar -xvf filename.tar.bz2

В данном случае архив filename.tar.bz2 будет распакован в ту папку, в которой вы находились в момент запуска команды. Для того, чтобы распаковать архив в какую-либо другую директорию, можно использовать команду:

tar -xvf filename.tar.bz2 -C /path/to/folder

В этом случае архив распакуется в указанной директории.
Просмотр содержимого архива без распаковки

Для этих целей используется следующая команда:

tar -tf filename.tar.gz

В результате выполнения команды выведется список файлов и папок, хранящихся в архиве. Если в перечень параметров добавить -v, то получится расширенный вывод информации о содержимом с указанием размера файлов, прав доступа, именами владельцев и их групп, и т.п.

Просмотреть полный список возможностей архиватора tar можно при помощи команд:

tar --help      #вызов справки по командам и параметрам
man tar	        #вызов расширенной документации

Создание и распаковка ZIP-архивов

Создание zip-архива выполняется командой:

zip archive.zip filename

Вместо archive.zip указываем имя создаваемого архива. Вместо filename указываем имя файла, который нужно архивировать. Для архивации целой папки необходимо использовать параметр –r, который инициирует рекурсивное архивирование. Без этого параметра будет заархивирована только папка без вложенных в неё файлов. Пример команды:

zip –r archive.zip dirname

Распаковка архива производится командой unzip:

unzip archivename.zip

Если необходимо распаковать в конкретную папку, то для этого используется параметр –d. Например:

unzip –d dirname archivename.zip

Вместо dirname указывается папка, в которую нужно извлечь данные из архива.

Просмотреть полный список возможностей архиватора zip и unzip можно при помощи команд:

zip --help или unzip --help	#вызов справки по командам и параметрам
man zip или man unzip		#вызов расширенной документации

Распаковка RAR-архивов

Для извлечения содержимого архива используется команда unrar:

unrar filename.rar

Посмотреть список файлов в архиве без его распаковки можно командой:

unrar –t filename.rar

Примечание: Стоит отметить, что Unrar может отсутствовать по умолчанию в некоторых Linux-дистрибутивах. Установить данное ПО можно следующими командами:

CentOS/Fedora:

yum install unrar

Debian/Ubuntu:

apt-get install unrar-free

Просмотреть полный список возможностей архиватора unrar можно при помощи команд:

rar --help 	#вызов справки по командам и параметрам
man unrar	#вызов расширенной документации
** Установка программ в Linux (.tar, .gz, .bz, RPM и DEB)
Установка программ на Debian, Ubuntu

Для работы с DEB пакетами существует множество инструментов, но пожалуй самый простой и часто используемый, это apt-get, входящий в стандартный набор инструментов. apt-get позволяет не только с легкостью устанавливать новые пакеты в систему, но и показывать какие пакеты доступны для установки и скачивать их с интернета в случае необходимости. Для установки приложения, введите в командную строку:

apt-get install имя_пакета

Для удаления:

apt-get remove имя_пакета

Несмотря на то, что содержимое пакетов может хранится на сервере в интернете или где нибудь на диске, APT хранит локальную базу данных со списком всех доступных для установки пакетов и ссылок где их брать. Эту базу необходимо периодически обновлять. Для обновления базы APT используется команда:

apt-get update

Очень часто программы изменяются (выходят обновления, патчи, системы безопасности и т.д.), можно также использовать APT для обновления устаревший пакетов (программ) в системе. Для обновления нужно сначала обновить список пакетов, а потом уже установить все обновления. Для этого выполняется следующая команда, которая сразу сделает все необходимое:

apt-get update; apt-get upgrade

Более подробную инструкцию по использованию утилиты APT можно посмотреть на официальном сайте.

Установка программ на Fedora, Red Hat

Для пакетов RPM есть замечательная утилита yum, которая делает примерно тоже самое, что и apt-get делает для пакетов Debian. Как и apt-get, yum позволяет загрузить и установить пакет из настроенного хранилища (репозитория):

yum install имя_пакета

Удалить программу также легко и просто:

yum remove имя_пакета

yum не сохраняет локальную базу данных списка пакетов, поэтому нет необходимости постоянно ее обновлять. Для установки всех доступных обновлений и патчей достаточно прописать команду:

yum update

или же выбрать определенную программу для обновления:

yum update имя_пакета

Установка программ в Mandriva

Mandriva Linux (бывший Mandrake и Connectiva) имеет свой набор инструментов для работы с пакетами установки, называется он urpmi. Для установки программ необходимо ввести:

urpmi имя_пакета

Для удаления:

urpme имя_пакета

Для обновления локальной базы данных списка пакетов:

urpmi.update -a

Для установки обновлений:

urpmi --auto-select

 Установка программ из архивов (тарболов)

Дистрибутив с программой, представляет из себя архив с кучей файлов и обычно имеет расширение  .tar , .tar.gz ,  .bz, .tgz ну или что то похожее.

Для архивов сжатых с помощью GZIP (gz, gz2 и т.д.) выполняем:

tar -xvzf имя_файла

Для архивов сжатых с помощью BZIP (bz, bz2 и т.д.) выполняем:

tar -xvjf имя_файла

Команды Tar:

    x — извлечь файлы из архива;
    v — подробный вывод информации на экран;
    f — Обязательная опция. Если не указать, Tar будет пытаться использовать магнитную ленту вместо файла;
    z — обработать архив сжатый gzip’ом;
    j — обработать архив сжатый bzip’ом.

После выполнения, будет создана папка с именем, идентичным названию пакета.

Далее необходимо открыть эту созданную папку

cd имя_папки

Далее все зависит от того, как была собрана программа, в виде исполняемого файла, или в исходном коде, который сначала необходимо скомпилировать и лишь потом устанавливать. В любом случае для начала лучше прочитать инструкцию, которая должна присутствовать в распакованном архиве и, как правило, называется README, или что то похожее.

Если программа собрана в виде исполняемого файла, то в папке будет находиться файл, с расширением .sh, обычно он так и называется install.sh. Его достаточно просто запустить на исполнение:

./install.sh

Если же программа представлено в исходном коде, выполняем следующие команды:

./configure
make
make install

После установки делаем:

make clean
** копирование файлов в Linux с помощью tar
Linux интересен тем, что позволяет выполнять одно и то же действие различными путями. Копирование в Linux тоже может быть выполнено не только с помощью cp. При переносе системных файлов в другой каталог, резервном копировании системных файлов и т.д. важно чтобы сохранились атрибуты, значения владельцев файлов и символические ссылки как они есть без какой-либо модификации.

Утилита cp тоже может справиться с такой задачей? если указать опцию -p, но можно использовать утилиту архивации tar. Мы не будем создавать никаких файлов архивов, а построим туннель. Первая часть команды пакует файл и отправляет на стандартный вывод, а другая сразу же распаковывает в нужную папку:

tar cf - /var | ( cd /mnt/var && tar xvf - )

Здесь мы полностью копируем содержимое папки /var в папку /mnt/var. Так вы можете копировать папку Linux, причём абсолютно любую или даже целую операционную систему.
