#+STARTUP: content

* LaTeX
** команды преамбула
C-c C-f C-b вставляет команду жирного шрифта \textbf{-!-}
    C-c C-f C-i вставляет команду шрифта italics \textit{-!-}
    C-c C-f C-e вставляет команду акцентирования (emphasized) \emph{-!-}
    C-c C-f C-s вставляет команду наклонного шрифта \textsl{-!-}
    C-c C-f C-r вставляет команду шрифта roman \textrm{-!-}
    C-c C-f C-f вставляет команду шрифта sans serif \textsf{-!-}
    C-c C-f C-t вставляет команду шрифта печатной машинки \texttt{-!-}}
    C-c C-f C-c вставляет команду шрифта SMALL CAPS \textsc{-!-}
    C-c C-f C-d удаляет окружающую команду изменения шрифта.}

    \documentclass - описывает класс документа, статья, книга, отчет и так далее;
    \begin - указывает на начало тела документа или блока;
    \end - завершение документа или блока;
    \usepackage - загружает пакет команд LaTeX в текущий документ, нужно для настройки кодировки, шрифта и другого;
    \maketitle - создает титульный лист с названием и всем прочим;
    \tableofcontents - содержание статьи или книги;
    \chapter - создает главу;
    \section - создает раздел;
    \subsection - создает подраздел;
    \bfseries - жирный текст;
    \textit - курсив;
    \title - заголовок документа;
    \author - автор документа;
    \date - дата создания документа.

стандартная преамбула:

\documentclass[a5paper,11pt]{report}
\usepackage[cp1251]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[english,russian]{babel}
\usepackage{amssymb,amsmath}
\usepackage[top=2cm,bottom=2cm,left=2cm,right=2cm]{geometry}
\oddsidemargin=30mm
\textwidth=110mm

\topmargin=20mm
\textheight=165mm

\begin{document}

Здесь Ваш текст...

\end{document}

на все случаи:

\documentclass[12pt,a4paper]{article}
%\documentclass[a4paper, 12pt, oneside]{ncc}
\usepackage[warn]{mathtext}          % русские буквы в формулах, с предупреждением
\usepackage[T2A]{fontenc}            % внутренняя кодировка  TeX
\usepackage[utf8x]{inputenc}         % кодовая страница документа
\usepackage[english, russian]{babel} % локализация и переносы
\usepackage{indentfirst}   % русский стиль: отступ первого абзаца раздела
\usepackage{misccorr}      % точка в номерах заголовков
\usepackage{cmap}          % русский поиск в pdf
\usepackage{graphicx}      % Работа с графикой \includegraphics{}
\graphicspath{{pictures/}}   % подключена папка с графикой
\DeclareGraphicsExtensions{.pdf,.png,.jpg}   % какие форматы подключены
\usepackage{psfrag}        % Замена тагов на eps картинкаx
\usepackage{caption2}      % Работа с подписями для фигур, таблиц и пр.
\usepackage{soul}          % Разряженный текст \so{} и подчеркивание \ul{}
\usepackage{soulutf8}      % Поддержка UTF8 в soul
\usepackage{fancyhdr}      % Для работы с колонтитулами
\usepackage{multirow}      % Аналог multicolumn для строк
\usepackage{ltxtable}      % Микс tabularx и longtable
\usepackage{paralist}      % Списки с отступом только в первой строчке
%\usepackage{longtable}
%\usepackage{tabularx}
\usepackage[perpage]{footmisc} % Нумерация сносок на каждой странице с 1
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{floatflt}      % Узкие  плавающие  иллюстрации  в  <оборку>  производятся  с  помощью  окружения floatingfigure 
\usepackage[a4paper, top=10mm, left=10mm, right=10mm, bottom=25mm]{geometry}
\usepackage[unicode, colorlinks=true]{hyperref}  % кликабельное содержание.рамка-colorlinks=true

\author{}
\title{Astra Orel 2.12\\(в картинках)}
\begin{document}
	\maketitle
	\center
	\tableofcontents
	\center
	\section{Системный монитор}	
	\includegraphics[scale=0.5]{astra/system}
    \flushright \textit{Сделано в \LaTeX.}
	
\end{document}
** PDFLaTeX in emacs
To compile documents to PDF by default add the following to your ~/.emacs.

    (setq TeX-PDF-mode t)
    c - c; c - c; retern(enter)

If it doesn’t work, try this :

    (require 'tex)
    (TeX-global-PDF-mode t)
** Проблема с LaTeX + utf8 + русский язык
texlive-core
texlive-bin 
texlive-langcyrillic - for LaTeX

Arch Linux: pacman -S texlive-most
Debian / Ubuntu / Mint: apt-get install texlive-full
Fedora: yum install texlive
** latex in rosa
urpmi --auto texlive # Компьютерная типография LaTeX
urpmi --auto texstudio # Оч. большой объём!
** install latex for all
 Использование менеджеров пакетов

    Arch Linux: pacman -S texlive-most
    Debian / Ubuntu / Mint: apt-get install texlive-full
    Fedora: yum install texlive 
