#+STARTUP: content

* Terminal

** Стандартные системные утилиты 
apt-listchanges
lsof
mlocate
w3m
at
libswitch-perl
xz-utils
telnet
dc
bsd-mailx
file
exim4-config
m4
bc
dnsutils
exim4
python2.7
openssh-client
aptitude
bash-completion
python
host
install-info
bzip2
reportbug
krb5-locales
bind9-host
time
info
liblockfile-bin
whois
aptitude-common
patch
ncurses-term
mutt
mime-support
exim4-daemon-light
ftp
nfs-common
python-reportbug
rpcbind
texinfo
python-minimal
procmail
libclass-isa-perl
python-apt
python-support
exim4-base
debian-faq
doc-debian
** Консольные программы
mc - файловый менеджер
mocp - аудиоплеер
htop - системный монитор
** Запуск консольных программ горячими клавишами(с клавиатуры)
название терминала+ -e+название программы-пример:
xfce4-terminal(konsole) -e mc(mocp)
** lsblk
lsblk -f подробней не куда…
** fdisk
# Выясняем, что за диски у нас есть.
# Сначала получим список устройств
$ ls -1 /dev/sd?
/dev/sda
/dev/sdb
# Теперь посмотрим какие разделы есть на диске "sda"
$ sudo fdisk -l /dev/sda
 ...
Устр-во       начало     Конец   Секторы Размер Тип
/dev/sda1       4096    618495    614400   300M EFI
/dev/sda2     618496 231612850 230994355 110,2G Файловая система Linux
/dev/sda3  231612851 250067789  18454939   8,8G Linux своп
# на диске "sdb"
$ sudo fdisk -l /dev/sdb
 ...
Устр-во    Загрузочный начало     Конец   Секторы Размер Идентификатор Тип
/dev/sdb1                2048 468860927 468858880 223,6G            83 Linux
# Куда примонтирован "sdb"
$ mount | grep /dev/sdb
/dev/sdb1 on /mnt/240 type ext4 (rw,noatime,discard)

Read more
man fdisk
** fdisk-создание_разделов(форматирование флешки)
fdisk /dev/sdX
o or g
n
4 раза [Enter]
w
Ваша флэшка восстановлена
** fdisk_и_vfat
ШАГ 1.Определить имя флешки
sudo fdisk -l или df

Шаг 2. Размонтирование флешки

Если флешка смонтирована в файловую систему, то форматировать её у вас не получится. Поэтому сначала нужно её размонтировать, для этого выполните:

 sudo umount /dev/sdb1

Здесь /dev/sdb1 - имя флешки в файловой системе, которое мы узнали в предыдущем шаге.
Шаг 3. Форматирование

Дальше отформатировать флешку очень просто. Для этого используется утилита mkfs. Синтаксис команды очень прост:

$ sudo mkfs -t файловая_система устройство

В качестве файловой системы может использоваться любая поддерживаемая системой, например, ext4, ntfs, xfs, btrfs, vfat. Но для нормальной работы флешки в Windows рекомендуется использовать файловую систему vfat. С помощью опции -L можно задать метку раздела. Тогда команда будет выглядеть вот так:

sudo mkfs -t ext4 -L FLASH /dev/sdb1

Для файловой системы vfat опция -L не поддерживается, вместо неё нужно использовать -n:

sudo mkfs -t vfat -n FLASH /dev/sdb1

После того, как форматирование флешки в Linux завершится, флешка будет готова к использованию.
** Rosa Grub2
fdisk -l
mount /dev/sdaX /mnt
grub2-install --root-directory=/mnt /dev/sda
update-grub2
Поправочка: Команду update-grub2 нужно выполнить в рабочей установленной системе на вашем компьютере после загрузки в неё.

Для Debian,Ubuntu команды:

grub-install --root-directory=/mnt /dev/sda
** Создание образа раздела
Создание образа раздела

 sudo dd if=/dev/sda4 of=~/backup.img

Здесь /dev/sda4 - это ваш корневой раздел. После завершения выполнения команды вы получите готовый образ, затем, чтобы восстановить систему из этой копии достаточно поменять опции местами и указать путь к файлу копии:

sudo dd if=~/backup.img of=/dev/sda4
** Создание образа диска с dd
Создание образа жесткого диска
dd if=/dev/sda of=/mnt/backup/sda.img bs=8M conv=sync,noerror

    if=/dev/sda - копируем весь жесткий диск sda;
    of=/mnt/backup/sda.img - копируем в /mnt/backup/sda.img;
    bs=8M - задаем размер кэша жесткого диска для ускорения процедуры копирования (иначе данные будут сбрасываться малыми порциями по 512 байт);
    conv=sync,noerror - указываем dd на необходимость копирования по типу бит-в-бит с игнорированием ошибок чтения.

Для сокращения размера образа жесткого диска его можно сжать любым архиватором.
dd if=/dev/sda bs=8M conv=sync,noerror | gzip -c > /mnt/backup/sda.img
Восстановление образа жесткого диска

Для восстановления образа жесткого диска необходимо проделать процедуру обратную процедуре создания этого образа.
dd if=/mnt/backup/sda.img of=/dev/sda bs=8M conv=sync,noerror

При использовании сжатия параллельно необходимо разархивировать образ.
gunzip -c /mnt/backup/sda.img | dd of=/dev/sda conv=sync,noerror bs=8M
Миграция системы на другой жесткий диск

Для миграции всей системы на другой жесткий диск необходимо, в качестве цели назначения задать расположение нового диска.
dd if=/dev/sda of=/dev/sdb bs=8M conv=sync,noerror

После чего при необходимости устанавливаем загрузку с данного жесткого диска. При условии, что новый жесткий диск больше старого, на нем останется неразмеченная область. Ее следует разметить и отформатировать согласно имеющимся требованиям.
** backup disk
Для выполнения резервной копии наберите такую команду:

dpkg --get-selections | grep -v deinstall > backup.txt

когда система сломается, переустановите ее с установочного носителя, а затем просто выполните команды:

sudo dpkg --set-selections < backup.txt

sudo apt-get -y update
$ sudo apt-get dselect-upgrade

СОЗДАНИЕ ОБРАЗА РАЗДЕЛА

Утилита просто переносит весь диск по одному байту в образ. Команда выглядит вот так:

sudo dd if=/dev/sda4 of=~/backup.img

чтобы восстановить систему из этой копии достаточно поменять опции местами и указать путь к файлу копии:

sudo dd if=~/backup.img of=/dev/sda4


!!!создать полную резервную копию системы Linux с помощью утилиты Rsync

Для начала, нам нужен резервный носитель (USB-флешка или внешний жесткий диск). 
Далее нужно узнать имя диска, используя команду «fdisk -l». В моем случае диск 
определился как /dev/sdb1. Теперь примонтируем наш резервный накопитель в любое 
удобное место, я выбрал /mnt.

$ sudo mount /dev/sdb1 /mnt

Чтобы создать резервную копию всей системы, все, что вам нужно сделать, это 
открыть терминал. Затем запустить в нем следующую команду от имени пользователя 
root:

$ sudo rsync -aAXv / 
--exclude={"/dev/*","/proc/*","/home/*","/sys/*","/tmp/*","/run/*","/mnt/*","/
media /* ","/lost+found"} /mnt

Эта команда создаст резервную копию всей корневой директории (/), исключая 
директории /dev, /proc, /sys, /tmp, /run, /mnt, /media,  lost + found в папке / 
mnt.

    rsync — быстрая, универсальная, локальная и удаленная утилита копирования 
файлов.
    -aAXv — файлы передаются в режиме «архив», что гарантирует сохранение 
символических ссылок, устройств, разрешений, владельцев, времени модификации, 
списков ACL и расширенных атрибутов.
    / — Исходный каталог.
    —exclude — исключает заданные каталоги из резервной копии.
    /mnt — это папка назначения резервного копирования.


    Обязательно исключите целевой каталог, если он существует в локальной 
системе, иначе будет бесконечный цикл копирования.

Чтобы восстановить систему из резервной копии, просто измените исходные и 
целевые пути в приведенной выше команде.
** ISO
ЕСЛИ ХОТИТЕ ВИДЕТЬ ПРОЦЕСС СОЗДАНИЯ ФЛЕШКИ, ТО ТУТ ЕСТЬ НЕСКОЛЬКО ПУТЕЙ. ПЕРВЫЙ ПУТЬ Я НЕ БУДУ РАССКАЗЫВАТЬ, ПОТОМУ КАК ОН МНЕ НЕ ПОНРАВИЛСЯ, А ВОТ АЛЬТЕРНАТИВНОЕ РЕШЕНИЕ ЭТОЙ ПРОБЛЕМЫ ВЫГЛЯДИТ НАМНОГО ЛУЧШЕ. ДЛЯ ЭТОГО НУЖНО БУДЕТ УСТАНОВИТЬ УЛУЧШЕННУЮ ВЕРСИЮ DD, КОТОРАЯ НОСИТ НАЗВАНИЕ DCFLDD.

SUDO APT-GET INSTALL DCFLDD

СОТРУДНИКИ ЛАБОРАТОРИИ DOD COMPUTER FORENSICS LABORATORY (DCFL) внесли некоторые изменения в команду dd, тем самым улучшив ее и применяя в своих исследовательских работах. В итоге на свет появилась команда dcfldd, которая обеспечивает хеширование копируемых данных через некоторые промежутки времени для их аутентификации. Более того, dcfldd работает гораздо быстрее, чем dd. Теперь, если Вы хотите именно видеть прогресс копирования, либо создания образа, Вам нужно выполнить команду:

sudo dcfldd if=/dev/sdc of=image.iso

Теперь, когда образ готов, можно создать новую, загрузочную флешку. Вставим вместо флешки с системами, новую, пустую. Думаю, что она определится системой так же, как и первая — sdc, но лучше перепроверить-sudo fdisk -l. Теперь команда будет такой:

sudo dd if=image.iso of=/dev/sdc status=progress
or 
sudo dd if=debian.iso of=/dev/sdx bs=4M && sync

Ну а если у Вас пустая флешка имеет тот же размер, что и носитель с нужными Вам данными, то можно просто скопировать все содержимое первой флешки сразу на вторую, минуя создание образа на жесткий диск. В этом случае команда будет следующей:

sudo dd if=/dev/sdb of=/dev/sdc


Как записать Manjaro Linux на флешку в Linux:
Самый простой способ записать Manjaro на флешку из терминала - это использовать утилиту dd. Команда будет выглядеть вот так:

sudo dd bs=4M if=/путь/к/manjaro.iso of=/dev/sd[буква_флешки] status=progress

Например:

sudo dd bs=4M if=~/Загрузки/manjaro.iso of=/dev/sdb status=progress

Посмотреть какая буква диска присвоена вашей флешке вы можете с помощью утилиты fdisk:

sudo fdisk -l

Anarchy Linux:
dd if=anarchy-{release}-x86_64.iso of=/dev/sdX status=progress && sync
sudo dd if=./<anarchy-image.iso> of=/dev/sdx bs=4M status=progress oflag=sync
** Монтирование флешек_mount
Команды:
sudo mkdir /media/flash
sudo fdisk -l

Команда монтирования флешки с ФС FAT16/32:
sudo mount -t vfat /dev/sdXX /media/flash -o uid=1000,utf8
или
sudo mount /dev/sdXX /media/flash -o uid=1000,utf8
или
sudo mount -t vfat /dev/sdXX /media/flash -o uid=1000,gid=1000,utf8,dmask=027,fmask=137

Команда монтирования флешки с ФС NTFS:

sudo mount -t ntfs-3g /dev/sdXX /media/flash
или
sudo mount /dev/sdXX /media/flash

где:
/dev/sdXX - раздел, который необходимо примонтировать;
/media/flash - папка, куда необходимо примонтировать раздел

Размонтировать:

sudo umount /dev/sdXX
где:
/dev/sdXX - раздел, который необходимо размонтировать
** Монтирование ISO Образа в Linux
Создадим точку монтирования:

$ sudo mkdir -p /mnt/mount_point

Монтирование ISO Файла в Linux

Смонтируем ISO файл /home/user/disk.iso в точку монтирования /mnt/mount_point:

$ sudo mount -o loop /home/user/disk.iso /mnt/mount_point

После того, как ISO образ диска будет смонтирован, Вы получите следующее сообщение: ‘mount: warning: /mnt/mount_point seems to be mounted read-only‘.

Можете спокойно его игнорировать, так как в соответствии со стандартом ISO 9660, ISO образы всегда монтируются только в режиме read-only (только чтение).
Проверяем что ISO Файл Смонтирован

Выведите список смонтированных устройств, чтобы убедиться что наш ISO образ успешно примонтировался:

$ mount

Внизу Вы должны увидеть строку на подобии следующей:

/home/user/disk.iso on /mnt/mount_point type iso9660 (ro)

Теперь Вы можете перейти в точку монтирования и просмотреть файлы содержащиеся на ISO образе диска:

$ cd /mnt/mount_point
$ ls -l

Размонтирование ISO Файла в Linux

Используйте следующую команду для размонтирования ISO образа диска:  sudo umount /dev/sdXX
** enp1s0
enp1s0
** узнать свой ip
   ip addr show
** date_and_time
%a - день недели, сокращенное название;
%A - день недели, полное название;
%w - номер дня недели, от 0 до 6;
%d - день месяца;
%b - сокращенное название месяца;
%B - полное название месяца;
%m - номер месяца;
%Y - номер года;
%H - час дня в 24 часовом формате;
%l - час дня в 12 часовом формате;
%p - AM или PM;
%M - минута;
%S - секунда.
** copy-paste xclip  xsel
xclip  xsel  утилиты копирования из буфера и в буфер в x11
** цвет фона терминала
#002B36 - цвет фона терминала
** youtube-dl
youtube-dl есть в каталогах пакетов некоторых дистрибутивов Linux: sudo apt-get install youtube-dl, sudo yum install youtube-dl, sudo pacman -S youtube-dl 

Итак, чтобы выкачать видео в максимальном разрешении и с наилучшим звуком, необходимо ввести команду вида 
youtube-dl https://www.youtube.com/watch?v=miVRaoR_8xQ

Скачивание плейлистов происходит аналогичным образом. Формат ссылки на плейлист — https://www.youtube.com/playlist?list=PL94A83DC128CC6B4B, то есть нужно зайти на главную страницу плейлиста. Осторожно: youtube-dl выкачает все видео в плейлисте.

Скачивание плейлистов происходит аналогичным образом. Формат ссылки на плейлист — https://www.youtube.com/playlist?list=PL94A83DC128CC6B4B, то есть нужно зайти на главную страницу плейлиста. Осторожно: youtube-dl выкачает все видео в плейлисте.

По флагу -F будут показаны все доступные форматы. Если ввести флаг -f с числовым кодом формата, он будет выкачан. Комбинация -f bestaudio выкачает аудио в лучшем формате.


Помимо того, чтобы получить список всех доступных форматов видео, которое вы хотите загрузить с утилитой youtube-dl, необходимо использовать вариант --list-formats, как показано ниже (пример):
youtube-dl --list-formats https://www.youtube.com/watch?v=ySzrJ4GRF7s

Я для примера выбрал формат под номером 18, с расширением mp4.Этот формат нужно добавить в команду после youtube-dl, как показано ниже в команде (пример):
 https://www.youtube.com/watch?v=ySzrJ4GRF7s

Другие возможности утилиты youtube-dl, можно посмотреть в терминале, выполнив команду:
youtube-dl --help

Для скачивания всего плейлиста, достаточно ввести ссылку на плейлист:

$ youtube-dl -Acitf 18  http://www.youtube.com/playlist?list=ссылка-на-плейлист

-Acitf — это параметры, вот их расшифровка:

    -A — автонумерация.
    -с — в случае обрыва соединения, продолжит с момента обрыва, после повторного ввода команды в том же каталоге.
    -i — игнорирование ошибок.
    -t — назвать файл, так же как имя записи.
    -f 18 — выбор формата и качества (см. выше).

Если нужен только аудио трек, тогда введем аргумент -х:

$ youtube-dl -x http://www.ссылка-на-видео

автонумерация -(youtube-dlg)
%(autonumber)s.%(title)s.%(ext)s
** youtube-dll_commands
Чтобы скачать нужное видео с YouTube достаточно выполнить команду в Терминале:
youtube-dl ссылка_на_видео
Для выбора нужного видео формата и качества, используем параметр -F:
youtube-dl -F ссылка_на_видео
Должны увидеть примерно такой вывод:

youtube-dl -F https://www.youtube.com/watch?v=Pi4uQl_0T2w
[youtube] Setting language
[youtube] Pi4uQl_0T2w: Downloading webpage
[youtube] Pi4uQl_0T2w: Downloading video info webpage
[youtube] Pi4uQl_0T2w: Extracting video information
[info] Available formats for Pi4uQl_0T2w:
format code extension resolution note
171 webm audio only DASH webm audio , audio@ 48k (worst)
140 m4a audio only DASH audio , audio@128k
160 mp4 192p DASH video
242 webm 240p DASH webm
133 mp4 240p DASH video
243 webm 360p DASH webm
134 mp4 360p DASH video
244 webm 480p DASH webm
135 mp4 480p DASH video
247 webm 720p DASH webm
136 mp4 720p DASH video
248 webm 1080p DASH webm
137 mp4 1080p DASH video
17 3gp 176×144
36 3gp 320×240
5 flv 400×240
43 webm 640×360
18 mp4 640×360
22 mp4 1280×720 (best)

Напротив формата имеется цифра, например 22 : mp4 1280×720 (best), именно ее нужно использовать для выбора качества, после параметра -f:



youtube-dl -f 22 ссылка_на_видео

Чтобы скачать весь плейлист, нужно ввести ссылку на плейлист в команду:

youtube-dl -f 22 https://www.youtube.com/channel/UCQBEHg0j6baNS1Lya-L4BJw

Чтобы скачать видео в определенный каталог нужно зайти в эту директорию при помощи команды cd и выполнить команду для скачивания. Например:

cd /home/user/save_video

youtube-dl -citw https://www.youtube.com/channel/UC9FSFwSIfqQkePaU

Основные параметры youtube-dl:

-A — автонумерация.
-с — если произойдет обрыв соединения, то утилита продолжит скачивание с момента обрыва, после повторного ввода команды в том же каталоге.
-i — игнорировать ошибки.
-t — присвоить имя файлу такое же как и имя записи.
—audio-format — указать формат сохраняемого аудио файла (mp3, aac, wav, m4a, vorbis)
—audio-quality — качество аудио файла. 0 (лучше), 9 (хуже) для VBR или конкретный битрейт, например 128K (по умолчанию 5)
-f 22 — выбор формата и качества.
-w — не перезаписывать файл.
-s — симуляция скачивания. Файл не не скачивается и не сохраняется на жесткий диск.
-x — используем, если нужно скачать только звук.
-o — параметр указывает каталог для сохранения. По умолчанию программа скачивает в Домашнюю папку.
-a — возможность скачать группу файлов из текстового файла. Адреса нужных видео файлов вписываете в текстовый файл в таком порядке:

https://www.youtube.com/watch?v=JIrm0dHbCDU
https://www.youtube.com/watch?v=diT3FvDHMyo
https://www.youtube.com/watch?v=Fy7FzXLin7o

и сохраняем его в Домашнем каталоге присвоим имя, например, video.txt. Чтобы скачать весь этот список выполним команду:

youtube-dl -a video.txt

Чтобы скачать видео конкретного пользователя, в нашем случае BlackSilverUfa, выполним следующую команду:

youtube-dl -citw ytuser:BlackSilverUfa

Чтобы сохранить видео в нужный каталог используем ключ -P:

wget -P /home/user/save https://www.youtube.com/playlist?list=PLG4Fqn_lntSq

Чтобы скачать в папку с названием Пользователя и оригинальным именем файлов, выполним:

youtube-dl -ciw ytuser:UCBB7mGxCAfQYqLgqNukEbtg -o '%(uploader)s/%(title)s'

Скачать и пронумеровать файлы с оригинальным названием в Домашнюю папку:

youtube-dl -ciw ytuser:UCBB7mGxCAfQYqLgqNukEbtg -o '%(autonumber)s_%(title)s.%(ext)s' --autonumber-size 2

Скачать и пронумеровать файлы с оригинальным названием в каталог с именем Пользователя:

youtube-dl -ciw ytuser:UCBB7mGxCAfQYqLgqNukEbtg -o '%(uploader)s/%(autonumber)s_%(title)s.%(ext)s' --autonumber-size 2

Скачать только звук:

youtube-dl -x ytuser:UCBB7mGxCAfQYqLgqNukEbtg

Скачать только звук в формате mp3 и в лучшем качестве VBR в каталог с именем Пользователя с нумерацией файлов:

youtube-dl -ciw ytuser:UCBB7mGxCAfQYqLgqNukEbtg -x --audio-format mp3 --audio-quality 0 -o '%(uploader)s/%(autonumber)s_%(title)s.%(ext)s' --autonumber-size 2

Чтобы узнать все ключи и параметры утилиты выполните команду:

man youtube-dl

Команда для скачивания:
youtube-dl -Aciw адрес с ютуба

** wget
Опции
    -V (--version) - вывести версию программы
    -h (--help) - вывести справку
    -b (--background) - работать в фоновом режиме
    -o файл (--out-file) - указать лог файл
    -d (--debug) - включить режим отладки
    -v (--verbose) - выводить максимум информации о работе утилиты
    -q (--quiet) - выводить минимум информации о работе
    -i файл (--input-file) - прочитать URL из файла
    --force-html - читать файл указанный в предыдущем параметре как html
    -t (--tries) - количество попыток подключения к серверу
    -O файл (--output-document) - файл в который будут сохранены полученные данные
    -с (--continue) - продолжить ранее прерванную загрузку
    -S (--server-response) - вывести ответ сервера
    --spider - проверить работоспособность URL
    -T время (--timeout) - таймаут подключения к серверу
    --limit-rate - ограничить скорость загрузки
    -w (--wait) - интервал между запросами
    -Q (--quota) - максимальный размер загрузки
    -4 (--inet4only) - использовать протокол ipv4
    -6 (--inet6only) - использовать протокол ipv6
    -U (--user-agent)- строка USER AGENT отправляемая серверу
    -r (--recursive)- рекурсивная работа утилиты
    -l (--level) - глубина при рекурсивном сканировании
    -k (--convert-links) - конвертировать ссылки в локальные при загрузке страниц
    -P (--directory-prefix) - каталог, в который будут загружаться файлы
    -m (--mirror) - скачать сайт на локальную машину
    -p (--page-requisites) - во время загрузки сайта скачивать все необходимые ресурсы
____________________________

1. Загрузка файла

Команда wget linux скачает один файл и сохранит его в текущей директории. Во время загрузки мы увидим прогресс, размер файла, дату его последнего изменения, а также скорость загрузки:

wget http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz

2. Сохранить файл с другим именем

Опция -О позволяет задать имя сохраняемому файлу, например, скачать файл wget с именем wget.zip:

wget -O wget.zip http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz

3. Скачать несколько файлов

Вы можете скачать несколько файлов одной командой даже по разным протоколам, просто указав их URL:

wget http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz ftp://ftp.gnu.org/gnu/wget/wget-1.10.1.tar.gz.sig

4. Взять URL из файла

Вы можете сохранить несколько URL в файл, а затем загрузить их все, передав файл опции -i. Например создадим файл tmp.txt, со ссылками для загрузки wget, а затем скачаем его:

wget -i /wget/tmp.txt

5. Продолжить загрузку

Утилита wget linux рассчитана на работу в медленных и нестабильных сетях. Поэтому если вы загружали большой файл, и во время загрузки было потеряно соединение, то вы можете скачать файл wget с помощью опции -c.

wget -c http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz

6. Загрузка файлов в фоне

Опция -b заставляет программу работать в фоновом режиме, весь вывод будет записан в лог файл, для настройки лог файла используются специальные ключи wget:

wget -b -o ~/wget.log http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz

7. Ограничение скорости загрузки

Команда wget linux позволяет не только продолжать загрузку файлов, но и ограничивать скорость загрузки. Для этого есть опция --limit-rate. Например ограничим скорость до 100 килобит:

wget --limit-rate=100k ftp://ftp.iinet.net.au/debian/debian-cd/8.4.0/amd64/iso-dvd/debian-8.4.0-amd64-DVD-1.iso

9. Загрузить и выполнить

Вы, наверное, уже видели такие команды. wget позволяет сразу же выполнять скачанные скрипты:

wget -O - http://сайт/скрипт.sh | bash

Если опции -O не передать аргументов, то скачанный файл будет выведен в стандартный вывод, затем мы его можем перенаправить с интерпретатор bash, как показано выше.
10. Сохранить файл в папке

По умолчанию wget сохраняет файл в текущую папку, но это поведение очень легко изменить с помощью опции -P:

wget -P ~/Downloads/ http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz

14. Скачать сайт

Wget позволяет не только скачивать одиночные файлы, но и целые сайты, чтобы вы могли их потом просматривать в офлайне. Использование wget, чтобы скачать сайт в linux выглядит вот так:

wget --mirror -p --convert-links -P ./<Local-Folder> аддресс_сайт
________________________________________________________________________________________________

Чтобы скачать сайт целиком с помощью wget нужно выполнить команду:

http://site.com/

После выполнения данной команды в директорию site.com будет загружена локальная копия сайта http://site.com. Чтобы открыть главную страницу сайта нужно открыть файл index.html.
Рассмотрим используемые параметры:
-r	—	указывает на то, что нужно рекурсивно переходить по ссылкам на сайте, чтобы скачивать страницы.
-k	—	используется для того, чтобы wget преобразовал все ссылки в скаченных файлах таким образом, чтобы по ним можно было переходить на локальном компьютере (в автономном режиме).
-p	—	указывает на то, что нужно загрузить все файлы, которые требуются для отображения страниц (изображения, css и т.д.).
-l	—	определяет максимальную глубину вложенности страниц, которые wget должен скачать (по умолчанию значение равно 5, в примере мы установили 7). В большинстве случаев сайты имеют страницы с большой степенью вложенности и wget может просто «закопаться», скачивая новые страницы. Чтобы этого не произошло можно использовать параметр -l.
-E	—	добавлять к загруженным файлам расширение .html.
-nc	—	при использовании данного параметра существующие файлы не будут перезаписаны. Это удобно, когда нужно продолжить загрузку сайта, прерванную в предыдущий раз.
** rsync
cd /
tar cvpzf mysysbackup.tgz --exclude=/proc --exclude=/lost+found --exclude=/mysysbackup.tgz --exclude=/media --exclude=/home /
** rsync1
Некоторые общие параметры, используемые с командами rsync:

    -v: подробный вывод.
    -r: рекурсивно копирует данные (но не сохраняет временные метки и разрешения при передаче данных).
    -a: режим архива, позволяет рекурсивно копировать файлы, а также сохраняет символические ссылки, права доступа к файлам, права владения пользователей и групп и временные метки.
    -z: сжатие данных файла.
    -h: human-readable, информация на выводе в формате, удобном для чтения.

Копирование/синхронизация файлов и локальный каталог
Копирование/синхронизация файлов на локальном компьютере

Следующая команда синхронизирует файл на локальном компьютере из одного места в другое. В этом примере, имя файла backup.tar необходимо скопировать или синхронизировать в папку /tmp/backups/:

[root@sedicomm]# rsync -zvh backup.tar /tmp/backups/

created directory /tmp/backups

backup.tar

sent 14.71M bytes received 31 bytes 3.27M bytes/sec

total size is 16.18M speedup is 1.10

В приведенном выше примере вы можете увидеть, что если место назначения еще не существует, rsync автоматически создаст каталог для такого места назначения.
 
Копирование/синхронизация каталога на локальном компьютере

Следующая команда перенесет или синхронизирует все файлы из одного каталога в другой на одном компьютере. В этом примере, в папке /root/rpmpkgs находятся некоторые файлы пакета rpm, и мы хотим, чтобы этот каталог был скопирован в папку /tmp/backups/:

[root@sedicomm]# rsync -avzh /root/rpmpkgs /tmp/backups/

sending incremental file list

rpmpkgs/

rpmpkgs/httpd-2.2.3-82.el5.centos.i386.rpm

rpmpkgs/mod_ssl-2.2.3-82.el5.centos.i386.rpm

rpmpkgs/nagios-3.5.0.tar.gz

rpmpkgs/nagios-plugins-1.4.16.tar.gz

sent 4.99M bytes received 92 bytes 3.33M bytes/sec

total size is 4.99M speedup is 1.00


!!!Для начала, нам нужен резервный носитель (USB-флешка или внешний жесткий 
диск). Далее нужно узнать имя диска, используя команду «fdisk -l». В моем случае 
диск определился как /dev/sdb1. Теперь примонтируем наш резервный накопитель в 
любое удобное место, я выбрал /mnt.

$ sudo mount /dev/sdb1 /mnt

Чтобы создать резервную копию всей системы, все, что вам нужно сделать, это 
открыть терминал. Затем запустить в нем следующую команду от имени пользователя 
root:

$ sudo rsync -aAXvzh / --exclude={"/home/*","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} /mnt

Эта команда создаст резервную копию всей корневой директории (/), исключая 
директории /dev, /proc, /sys, /tmp, /run, /mnt, /media,  lost + found в папке / 
mnt.

Если вы хотите скопировать только измененные файлы, добавьте опцию -c

    rsync — быстрая, универсальная, локальная и удаленная утилита копирования 
файлов.
    -aAXv — файлы передаются в режиме «архив», что гарантирует сохранение 
символических ссылок, устройств, разрешений, владельцев, времени модификации, 
списков ACL и расширенных атрибутов.
    / — Исходный каталог.
    —exclude — исключает заданные каталоги из резервной копии.
    /mnt — это папка назначения резервного копирования.

—include и —exclude, с помощью этих опций, можно делать исключения по копированию директорий или файлов
Резервное копирование в Linux с помощью rsync

rsync -zvra --exclude=administrator/ /var/www/site root@IP:/backup/
В данном случае мы исключили директорию “administrator” при копировании на удаленный сервер.

# rsync -zvra --include='*.php' --exclude='*' /var/www/site/administrator/ root@IP:/backup/
Добавлением опции —include мы смогли задать фильтр по файлам, скопировали только файлы с расширением php.

В своей рабое я часть использую rsync для автоматических задач резервного копирования в Linux. Можно написать простые bash скрипты или просто добавить команду rsync в cron и выполнять по расписанию.

Например, можно добавить в cron команду:

01 30 * * * rsync -zvra root@IP:/backup/ /backup

В резульатате каждый день в 1-30 ночи, будет выполняться синхронизация каталогов локального и удаленного серверов.
** terminal  rsync
Некоторые общие параметры, используемые с командами rsync:

    -v: подробный вывод.
    -r: рекурсивно копирует данные (но не сохраняет временные метки и разрешения при передаче данных).
    -a: режим архива, позволяет рекурсивно копировать файлы, а также сохраняет символические ссылки, права доступа к файлам, права владения пользователей и групп и временные метки.
    -z: сжатие данных файла.
    -h: human-readable, информация на выводе в формате, удобном для чтения.

Копирование/синхронизация файлов и локальный каталог
Копирование/синхронизация файлов на локальном компьютере

Следующая команда синхронизирует файл на локальном компьютере из одного места в другое. В этом примере, имя файла backup.tar необходимо скопировать или синхронизировать в папку /tmp/backups/:

[root@sedicomm]# rsync -zvh backup.tar /tmp/backups/

created directory /tmp/backups

backup.tar

sent 14.71M bytes received 31 bytes 3.27M bytes/sec

total size is 16.18M speedup is 1.10

В приведенном выше примере вы можете увидеть, что если место назначения еще не существует, rsync автоматически создаст каталог для такого места назначения.

 
Копирование/синхронизация каталога на локальном компьютере

Следующая команда перенесет или синхронизирует все файлы из одного каталога в другой на одном компьютере. В этом примере, в папке /root/rpmpkgs находятся некоторые файлы пакета rpm, и мы хотим, чтобы этот каталог был скопирован в папку /tmp/backups/:

[root@sedicomm]# rsync -avzh /root/rpmpkgs /tmp/backups/

sending incremental file list

rpmpkgs/

rpmpkgs/httpd-2.2.3-82.el5.centos.i386.rpm

rpmpkgs/mod_ssl-2.2.3-82.el5.centos.i386.rpm

rpmpkgs/nagios-3.5.0.tar.gz

rpmpkgs/nagios-plugins-1.4.16.tar.gz

sent 4.99M bytes received 92 bytes 3.33M bytes/sec

total size is 4.99M speedup is 1.00
** xine
0..9 - устанавливают просмотр на позицию 10%..90%
    A - установить режим просмотра AUTO/16:9/4:3/DBV
    Alt +c - вывести/спрятать окно настройки видео
    F - переключение в широкоэкранный режим и обратно
    G - убрать/показать графический интерфейс
    H - тоже самое с окном воспроизведения (очень выручает, когда начальник входит)
    Ctrl+m - включение/выключение звука
    t - снять snapshot
    Enter - воспроизведение
    Пробел - пауза
    вверх/вниз - увеличение/уменьшение скорости воспроизведения
    </> - увеличить/уменьшить размер
    Alt+1[2,3] - установить размер окна воспроизведения равным 50%[100%,200%]
    n/m - позволяют догнать видео/аудио при асинхронном воспроизведении
    Q - выход 
** Vimium C
  Vimium C-это расширение для браузера с открытым исходным кодом, которое обеспечивает клавиатурную навигацию по внутренней странице, Операции с вкладками браузера и расширенную панель поиска, так что вы можете в полной мере использовать преимущества своего браузера без мыши или сенсорной панели.

Он поддерживает:
 нажмите клавишу "f", чтобы подсказать все кликабельные элементы текущей веб-страницы
 нажмите " o`, чтобы показать панель поиска ("Vomnibar", безопасный iframe) для поиска в вашей истории, закладках, открытых вкладках и настроенных поисковых системах, и вы даже можете удалить историю или вкладку, выбрав результат поиска и нажав Shift+Delete
 нажмите j, k, h, l для прокрутки вниз/вверх/влево/вправо на веб-страницах
 нажмите "/" для поиска текста; нажмите "v" для входа в визуальный режим (так же, как VIM)
 нажмите Shift+J, Shift+K, `g0`, `g$`, чтобы переключиться на предыдущую/следующую/первую/последнюю вкладку
 нажмите "x", чтобы удалить вкладку, и Shift+X, чтобы восстановить недавно закрытые вкладки (сеансы), и многие другие команды
 повторение команды: например, нажатие кнопки `5X` (`5`, Shift+X) восстановит 5 последних закрытых вкладок
 настройте сопоставления клавиш для привязки десятков команд Vimium C к другим последовательностям клавиш и добавьте опции для переключения поведения команд.
 применяются списки запрещенных и разрешенных списков клавиш настраивается на специальных веб-сайтов и URL-адресов

Он может скопировать любой выделенный текст, заголовок текущей вкладки и URL-адрес в системный буфер обмена, а также прочитать буфер обмена для поиска скопированного текста с помощью указанной поисковой системы.

Он также может включать/отключать загрузку изображений веб-сайтов и даже выполнение JavaScript, если вы запускаете его команду "toggleCS". Эта функция требует разрешения "изменить настройки, которые контролируют доступ веб-сайтов к таким функциям, как файлы cookie, JavaScript...", и Vimium C обещает, что он ничего не будет делать тайно, а только действовать в соответствии с тем, какие последовательности клавиш вы нажимаете.

Он будет предоставлять 8 "глобальных" ярлыков браузера: createTab, previousTab, nextTab, reloadTab и некоторые другие, поэтому вы можете привязать к ним некоторые последовательности клавиш, и тогда эти команды будут работать даже тогда, когда страница не имеет фокуса (например, когда адресная строка браузера сфокусирована).
** alsamixer
Открыть микшер ALSA можно в терминале, введя команду alsamixer.выбрать нужную звуковую карту, нажав клавишу F6
** Погода в терминале
curl wttr.in/Петропавловск-Камчатский
** Googler-googl in terminal
Google - одна из лучших поисковых систем, используемая сегодня, и она знакома многим из нас. Вы можете использовать Googler для поиска в Google непосредственно из командной строки. Что мне действительно нравится в Googler, так это то, что он показывает результаты поиска без рекламы!

Установка Гуглера
Кроме того , вы должны будете иметь Python 3.5, а также xsel, xclip или termix-clipboard-set для того, чтобы иметь возможность скопировать URL - адрес в буфер обмена. Эти пакеты можно установить из диспетчера пакетов вашего дистрибутива, если они еще не установлены.

Самый простой способ установить Googler заключается в следующем:

sudo curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/v4.0/googler
sudo chmod +x /usr/local/bin/googler


Использование Googler
Использование Googler так же просто, как и ddgr. Чтобы что-то искать, просто введите, googler, а затем ваш поисковый запрос. Например, если бы я хотел узнать, что то, о Linux, я бы набрал следующее:

googler linux

Если вы хотите открыть конкретный результат, просто введите число, соответствующее результату поиска, и нажмите ввод. Для продвижения страницы результатов поиска вперед, введите n и нажмите Enter. Чтобы вернуться, введите p. Если вы хотите перейти на первую страницу результатов поиска по определенному поисковому запросу, введите f и нажмите Enter.
** Calcurs-консольный календарь
Calcurse — консольный календарь. С календарём Google не синхронизируется, но в остальном предоставляет неплохую функциональность. Позволяет создавать события и писать списки дел. Имеется в нём и система уведомлений.

sudo apt install calcurse

calcurse
** Как вытянуть звук из видео файлов
mkdir cash
for f in *.avi *MOV *.mkv *.mp4 *.mpg ;
do
ffmpeg -i "$f" -vn -ar 44100 -ac 2 -ab 192k -f mp3 cash/"${f%.*}".mp3
done
В этой же папке появится директория Cash, в которой и будут находится извлеченные звуковые дорожки. Этот скрип можно применять к видео файлам, которые имеют следующие расширения: .avi, MOV, .mkv, .mp4 , .mpg. Кстати, проблема пробелов, в названии файлов, в данном скрипте решена.

или 

#!/bin/sh
mkdir cash
for f in *.avi *MOV *.mkv *.mp4 *.mpg ;
do
ffmpeg -i "$f" -vn -ar 44100 -ac 2 -ab 64k -f mp3 cash/"${f%.*}".mp3
done
** Конвертирование музыки в utf-8
Конвертирование музыкальной библиотеки в кодировку utf-8.

Для полного конвертирования всей музыкальной библиотеки будем использовать скрипт mid3iconv, который поставляется в комплекте пакета python-mutagen. Для правильной работы пакет python-mutagen должен быть версией не ниже 1.1.

    Устанавливаем пакет python-mutagen:
    Debian, Ubuntu, Kubuntu..:
    # sudo apt-get install python-mutagen
    Переходим в директорию с Вашей музыкальной библиотекой:
    # cd /home/ВАШ_ЛОГИН/Музыка
    Возможно директория с музыкальной библиотекой у Вас будет другой.
    Конвертируем библиотеку:
    # find -iname '*.mp3' -print0 | xargs -0 mid3iconv -eCP1251 --remove-v1
** mp3unicode
mp3unicode
*.mp3 это шаблон, для работы mp3unicode необходим пакет libtag (библиотека для работы с тегами).

mp3unicode --source-encoding cp1251 --id3v1-encoding none --id3v2-encoding unicode *.mp3

Рекурсивная перекодировка каталога музыкальной коллекции, выполнить:

find . -name "*.mp3" -exec mp3unicode -s cp1251 -2 unicode {} \;
** net-tools_ifconfig
Набор утилит net-tools считается устаревшим, рекомендуется использовать вместо него пакет iproute2

 	ifconfig-старая команда 	ip address,ip link-новая команда
** Чистим систему
sudo apt-get autoclean
рекомендуется делать эту команду периодически, очищая систему от .deb пакетов, которые более не нужны,

sudo apt-get autoremove
данная команда удаляет неудалённые зависимости от уже удалённых пакетов,

sudo apt-get clean
очистка каталога /var/cache/apt/archives/ .
** проба оборудования(в Rosa)
sudo -E hw-probe -all -upload 
** Вывод систем.ошибок in log file
dmesg  > dmesg.txt

journalctl  >  journalctl.txt

systemctl status NetworkManager

systemctl list-unit-files

Получение информации о текущих целях

В systemd для этого предназначена следующая команда (заменяющая runlevel):

$ systemctl list-units --type=target
** Дата и время установки ОС Linux
Дата и время установки ОС Linux из свойств файловой системы
Для этого, необходимо выполнить данную команду с root правами:

sudo tune2fs -l $(df / | tail -1 | cut -f1 -d' ') | grep created

В итоге мы должны получить что то вроде этого:
** узнать сетевую карту
Перед тем как работать с сетью, иногда (а лучше всегда) необходимо узнать какая сетевая карта установлена в системе, например решать вопросы совместимости довольно трудно не зная модель сетевой карты. Проще всего использовать для этого утилиту lshw. Установим её и запустим:

sudo pacman -S lshw 
sudo lshw -C network 
** все подключения инета
sudo pacman -S tcptrack
sudo tcptrack -i enp1s0
узнать все подключения
** touch_создать файл
Чтобы создать пустой файл Linux, просто наберите:
touch файл.txt
** Команда cp_создать файл
Команда cp используется для копирования файлов в Linux. Но с её помощью можно и создать файл. Например, чтобы создать пустой файл, можно просто скопировать /dev/null:

cp /dev/null файл
** список всех пакетов в файл
sudo dpkg - -get-selections "*" > /home/user/my_packages.txt
— список всех пакетов в файл

установка пакетов из полученного файла —---»
sudo dpkg - -set-selections < /home/user/my_packages.txt
sudo apt-get -u dselect-upgrade
** Как в Linux вывести список установленных пакетов
Для RPM пакетов

Для дистрибутивов, использующих RPM пакеты (CentOS, OpenSUSE, Fedora и другие), выполните следующую команду:

rpm -qa --queryformat '%10{size} - %-25{name} \t %{version} \t %{os} \n' | sort -rh | head -30 | awk '{print $1/1024/1024, $2, $3, $4}'
** Команды обновления системы(debian...)
$ sudo apt update 
$ sudo apt upgrade
$ sudo apt dist-upgrade

$ sudo apt autoremove

$ sudo do-release-upgrade -d
** Удаление программ
В Ubuntu, Debian, Linux Mint и других дистрибутивах этого семейства команда будет выглядеть вот так:

sudo apt remove firefox

Эта команда удалит пакет из системы, но некоторые конфигурационные файлы останутся и будут занимать место. Чтобы полностью удалить программу используйте опцию purge:

sudo apt purge firefox

А чтобы, также удалить зависимости, установленные вместе с пакетом, нужно после одной из предыдущих команд выполнить:

sudo apt-get autoremove


Удаление программы на Ubuntu 16.04 с помощью команды 
1.) dpkg --list     - проверить список установленных программ
2.) sudo apt-get --purge remove имя_программы    - удалить программу и файлы настроек
3.) sudo apt-get remove имя_программы     - удалить только саму программу
** компиляция программ из исходников

Установить программное обеспечение из исходного кода:

tar zxvf [source_code.tar.gz]
cd [source_code]
./configure
make

** Сборка пакетов из исходников
 Создать кваталог ~/.build и перейти в него.

mkdir ~/.build && cd ~/.build

Найти нужный пакет на сайте aur.archlinux.org и загрузить snapshot.

wget https://aur.archlinux.org/cgit/aur.git/snapshot/gtk3-mushrooms.tar.gz

Распаковываем, переходим в каталог, собираем пакет и устанавливаем.

tar -xvzf gtk3-mushrooms.tar.gz
cd gtk3-mushrooms
makepkg -sri

Если вылазят ошибки ключей, можно проигнорировать.

makepkg -s --skippgpcheck

После сборки появится пакет с расширением имя.pkg.tar.xz Установить командой.

sudo pacman -U имя.pkg.tar.xz
** Скорость интернета
Узнать скорость интернета не выходя из терминала можно узнать командой:
speedtest-cli
** найти IP-адрес сервера в терминале
$ curl ifconfig.co
$ curl ifconfig.me
$ curl icanhazip.com

120.88.41.175

 wget -qO- http://ipecho.net/plain | xargs echo
$ wget -qO - icanhazip.com

120.88.41.175
** Автоматический вход в систему
 SDDM поддерживает автоматический вход. Для этого настройте конфигурационный файл, например:

/etc/sddm.conf.d/autologin.conf

[Autologin]
User=ivan
Session=plasma.desktop

Эта конфигурация позволит автоматически запускать KDE Plasma для пользователя ivan при загрузке системы. Все доступные сеансы доступны в директории /usr/share/xsessions/. 
** Быстрое выключение компа in xfce
xfce4-session-logout -h
** подключение смартфона
gvfs-mtp установлен, Samsung видит

    Для файловых менеджеров, которые используют GVFS (GNOME Files, Xfce's Thunar), установите gvfs-mtp для поддержки MTP и gvfs-gphoto2 для поддержки PTP.
    Для файловых менеджеров, которые используют KIO (KDE's Dolphin), установите kio-mtp[ссылка недействительна: сохранено в aur-mirror] (поддержка PTP уже включена в него).

Также существует альтернатива плагинам: минималистичный MTP клиент android-file-transfer. 

Примечание: Если у вас более новое Android устройство, которое не поддерживает UMS (USB-накопитель) и вы считаете что mtpfs очень медленный или работает некорректно, то вы можете установить jmtpfsAUR из AUR.
** сведения о компьютере
sudo lshw
sudo lshw -short

Немного дополним предыдущую команду.
sudo lshw -html > system_info.html

И в домашней директории появился файл system_info.html, который мы сможем просмотреть в любом интернет браузере.
** иксы и minimalde
Ставим иксы и драйвера

#Установим  Х (Иксы) и свободные драйвера + читаем зависимости при необходимости ставим их тоже
pacman -S xorg-server xorg-drivers

Установка

MATE доступен в официальных репозиториях и может быть установлен одним из следующих способов:

    Пакет mate-panel предоставляет минимальное окружение рабочего стола.
    Группа пакетов mate содержит основное рабочее окружение и приложения, необходимые для стандартной работы MATE
    Группа пакетов mate-extra содержит различные необязательные инструменты, которые хорошо работают в MATE. Заметьте, что установка только группы пакетов mate-extra не вытянет всю группу mate зависимостями: если вы действительно хотите всё, вы должны установить обе группы


    Установка
    KDE Plasma
    Примечание: Перед тем, как устанавливать KDE Plasma, убедитесь, что в вашей системе установлен и настроен сервер Xorg.
    
    Установите мета-пакет plasma-meta или группу пакетов plasma. Для получения информации о различиях между ними смотрите статью Группа пакетов.
    
    Если вам нужна более минималистичная Plasma (с меньшим количеством установленных пакетов и приложений), установите пакет plasma-desktop.
    
    Для поддержки Wayland также требуется установить пакет plasma-wayland-session.
    Приложения KDE
    
    Чтобы установить все приложения KDE (KDE Applications), установите группу пакетов kde-applications или мета-пакет kde-applications-meta. Обратите внимание, что установятся только Приложения KDE, а не среда рабочего стола KDE Plasma. 



Установка

LXDE модульный и вы можете выбирать только те пакеты, которые вам нужны.

Минимально необходимые пакеты для запуска LXDE: lxde-common, lxsession, desktop-file-utils и оконный менеджер.

Вы можете установить группу пакетов LXDE:

# pacman -S lxde

Установятся следующие пакеты:

    gpicview: Простой и легкий просмоторщик изображений
    libfm: Библиотека для работы с файлами (lxshortcut: Простое средство редактирования ярлычков)
    lxappearance: Редактор тем для изменения GTK+ тем, иконок и шрифтов для приложений GTK
    lxappearance-obconf: Плагин для настройки Openbox через LXAppearance
    lxde-common: Установки по умолчанию конфигурационных файлов для большинства интегрированных компонентов LXDE
    lxde-icon-theme: Тема значков LXDE
    lxdm: Легковесный менеджер дисплея приветствия
    lxinput: Конфигурационная утилита для клавиатуры и мышки в LXDE
    lxlauncher: Панель запуска приложений для нетбуков
    lxmenu-data: Коллекция файлов адаптирующая меню LXDE под стандарты спецификации freedesktop.org
    lxmusic: Минималистичный проигрыватель музыки базирующийся на xmms2
    lxpanel: Панель задач с менеджером приложений, меню программ и апплетов
    lxrandr: Менеджер экрана для LXDE
    lxsession: Совместимый X11 менеджер сессий с поддержкой выключения, перезагрузки и ждущего режима
    lxtask: Диспетчер задач и системный монитор LXDE
    lxterminal: Стандартный эмулятор терминала для LXDE
    menu-cache: Механизм кеширования для freedesktop.org-совместимых меню
    openbox: Легкий и удобно конфигурируемый менеджер окон (рекомендуемый менеджер, разработанный вне проекта LXDE).
    pcmanfm: Файловый менеджер, функционал рабочего стола и обоев

Вам также следует установить Gamin. Gamin - это инструмент для отслеживания изменений в файлах и директориях, который является реализацией подсистемы FAM. Запуск производится по требованию программ, которые им поддерживаются, поэтому не требуется отдельно демона, подобного FAM. Если у Вас установлен FAM - удалите запуск этого демона из /etc/rc.conf и остановите его перед установкой Gamin

pacman -S gamin

Другие легковесные приложения, которые рекомендуется использовать на слабых системах:

    leafpad: Простой и легкий текстовый редактор
    mousepad: Простой текстовый редактор (является текстовым редактором по умолчанию среды Xfce)
    xarchiver: Легкий архиватор
    obconf: Инструмент для настройки тем и стилей Openbox
** команды из консоли(файловые менеджеры)
В дебе пользую apt-get, в Росе urpmi, в арче pacman
** Установка deb пакета через терминал
то есть, для установки deb пакета через терминал нужно использовать конструкцию:
	sudo dpkg -i имя_пакета.deb
** Как узнать версию Debian
1. Краткое наименование дистрибутива. Выясняется командой:

# cat /etc/issue.net

Debian GNU/Linux jessie/sid

2. Полная информация о дистрибутиве: 

# lsb_release -a

No LSB modules are available.

Distributor ID: Debian

Description:    Debian GNU/Linux testing (jessie)

Release:        testing

Codename:       jessie

3. Архитектура (разрядность) дистрибутива

# uname -m

i686

4. Версия ядра

# uname -a

Linux pangolinux 3.2.0-4-686-pae #1 SMP Debian 3.2.32-1 i686 GNU/Linux

5. Узнать каким компилятором было собрано ядро:

# cat /proc/version

Linux version 3.2.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-12) ) #1 SMP Debian 3.2.32-

6. Информация о версии дистрибутива, записанная разработчиками:

# cat /etc/*-release

PRETTY_NAME="Debian GNU/Linux jessie/sid"

NAME="Debian GNU/Linux"

ID=debian

HOME_URL="http://www.debian.org/"

SUPPORT_URL="http://www.debian.org/support/"

BUG_REPORT_URL="https://bugs.debian.org/"

7. Краткая информация о версии Debian, из специально предназначенного для этого файла:

# cat /etc/debian_version

jessie/sid
** узнать размер папки
Для того, чтобы узнать размер папки, используйте команду:

    du -sh  - размер текущей папки

    du -sh /путь/к/папке
** узнать размер файла
    du -h /путь_к_файлу/имя файла

    du -h ./имя файла  - если файл находится в той же папке, в которой вы находитесь
** как узнать uuid диска linux
как узнать uuid диска linux

ls -la /dev/disk/by-uuid/

Ещё один вариант - эту утилита lsblk, которая тоже может показывать UUID:

lsblk -o +uuid,name

ls -l /dev/disk/by-uuid/
** узнать размер диска_dev-sda
Узнать размер диска, занятое и свободное место

    df -ah
** Узнать свою видеокарту
lspci -vnn | grep VGA -A 12

** смена прав в MC

Права доступа (<Ctrl>+<X>,<C>). Позволяет изменить права доступа к выделенному или помеченным файлам.

Владелец/группа (<Ctrl>+<X>,<O>). Позволяет выполнить команду chown.

Права (расширенные). Позволяет изменить права доступа и владения файлом.

Жесткая ссылка (<Ctrl>+<X>,<L>). Создает жесткую ссылку на текущий файл.

Символическая ссылка (<Ctrl>+<X>,<S>). Создает символическую ссылку на текущий файл. О ссылках мы подробно говорили в разд. 4.4. Программа Midnight Commander указывает символические ссылки, выводя знак "@" перед именем такой ссылки (кроме ссылок на подкаталоги, которые обозначаются знаком тильды "~"). Если на экран выводится строка мини-статуса (опция "Показывать мини-статус" включена), то в ней отображается имя того файла, на который указывает ссылка.

Быстрая смена каталога (<Alt>+<C>). Используйте эту команду, если вы знаете полный путь к каталогу, в который хотите перейти (который хотите сделать текущим).
